---
# playbook to remove nginx
- hosts: webserver
  become: true
  tasks:
   - name: remove nginx
     apt: name=nginx state=absent
     tags: [ 'packages' ]
     notify:
      - stop nginx

  handlers:
   - name: stop nginx
     service: name=nginx state=stopped
