--- # Testing how variables work in the vars section of a playbook
- hosts: '{{ myhost }}'
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhost: app
    gather: yes
    pkg: telnet
  tasks:
  - name: Install the indicated software
    apt:
      name: '{{ pkg }}'
      state: latest
